"""Delta-A-Alpha V1 startup + observational learning interfaces (031).

This module is infrastructure ONLY. It cannot create trades, override the frozen
L0-L7 strategy or claim profit. The original layer decisions and L7 governor
remain authoritative. No future bars/outcomes and no forced warmup idle period.
"""
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

CONTRACTS = ("L0", "L1", "L2", "L3", "L4", "L5", "L6", "L7")
TIMEFRAMES = ("H4", "H1", "M15", "M5")
FIVE_MIN_MS = 300_000


class Phase(str, Enum):
    MARKET_CLOSED = "MARKET_CLOSED"
    HISTORY_REQUIRED = "HISTORY_REQUIRED"
    INFRASTRUCTURE_REQUIRED = "INFRASTRUCTURE_REQUIRED"
    READY_NO_SIGNAL = "READY_NO_SIGNAL"
    SIGNAL_ELIGIBLE = "SIGNAL_ELIGIBLE"


@dataclass(frozen=True)
class CompletedBarEvidence:
    timeframe: str
    completed_at_ms: int
    values_known: bool


@dataclass(frozen=True)
class StartupFrame:
    now_ms: int
    executable_quote: bool
    market_open: bool
    broker_ready: bool
    margin_checked: bool
    spread_acceptable: bool
    completed_bars: tuple[CompletedBarEvidence, ...]
    active_layer_contracts: tuple[str, ...]
    # Generated by the existing, original grid/HTF/hourly/native/Watchdog/recovery logic.
    original_v1_signal: bool = False
    governor_admits: bool = False


@dataclass
class StartupState:
    deployment_ms: int
    first_tradable_quote_ms: Optional[int] = None
    first_ready_ms: Optional[int] = None
    first_eligible_ms: Optional[int] = None
    first_funded_ms: Optional[int] = None
    latest_ms: Optional[int] = None
    phase: Phase = Phase.MARKET_CLOSED
    blockers: tuple[str, ...] = field(default_factory=tuple)

    @property
    def deadline_ms(self) -> Optional[int]:
        if self.first_tradable_quote_ms is None:
            return None
        return self.first_tradable_quote_ms + FIVE_MIN_MS

    @property
    def five_minute_readiness(self) -> str:
        """Separate system readiness from trade placement and profit outcomes."""
        if self.first_tradable_quote_ms is None:
            return "NOT_EVALUABLE_MARKET_NOT_YET_TRADABLE"
        if self.first_ready_ms is not None:
            return "PASS" if self.first_ready_ms <= self.deadline_ms else "FAIL_LATE"
        if self.latest_ms is not None and self.latest_ms >= self.deadline_ms:
            return "FAIL_INCOMPLETE_INITIALIZATION"
        return "PENDING"


class StartupGate:
    def __init__(self, deployment_ms: int):
        self.state = StartupState(deployment_ms=deployment_ms)

    def observe(self, frame: StartupFrame) -> Phase:
        s = self.state
        if frame.now_ms < s.deployment_ms:
            raise ValueError("No execution observations before as-of deployment T0")
        if s.latest_ms is not None and frame.now_ms < s.latest_ms:
            raise ValueError("Ticks must arrive in chronological order")
        s.latest_ms = frame.now_ms
        if not frame.market_open or not frame.executable_quote:
            s.phase = Phase.MARKET_CLOSED
            s.blockers = ("NO_EXECUTABLE_MARKET_QUOTE",)
            return s.phase
        if s.first_tradable_quote_ms is None:
            s.first_tradable_quote_ms = frame.now_ms
        evidence = {b.timeframe: b for b in frame.completed_bars}
        blockers = []
        for tf in TIMEFRAMES:
            b = evidence.get(tf)
            if b is None or not b.values_known or b.completed_at_ms > frame.now_ms:
                blockers.append("COMPLETED_" + tf + "_UNAVAILABLE")
        if blockers:
            s.phase = Phase.HISTORY_REQUIRED
            s.blockers = tuple(blockers)
            return s.phase
        if not frame.broker_ready:
            blockers.append("BROKER_NOT_READY")
        if not frame.margin_checked:
            blockers.append("MARGIN_NOT_CHECKED")
        if not frame.spread_acceptable:
            blockers.append("SPREAD_NOT_EXECUTABLE")
        missing = set(CONTRACTS) - set(frame.active_layer_contracts)
        if missing:
            blockers.extend("UNAVAILABLE_" + x for x in sorted(missing))
        if blockers:
            s.phase = Phase.INFRASTRUCTURE_REQUIRED
            s.blockers = tuple(blockers)
            return s.phase
        if s.first_ready_ms is None:
            s.first_ready_ms = frame.now_ms
        s.blockers = ()
        if not frame.original_v1_signal or not frame.governor_admits:
            s.phase = Phase.READY_NO_SIGNAL
        else:
            s.phase = Phase.SIGNAL_ELIGIBLE
            if s.first_eligible_ms is None:
                s.first_eligible_ms = frame.now_ms
        return s.phase

    def record_funded(self, time_ms: int) -> None:
        """Call ONLY after actual verified order acceptance. Not on shadow proposals."""
        s = self.state
        if s.phase != Phase.SIGNAL_ELIGIBLE or time_ms < (s.first_eligible_ms or 0):
            raise ValueError("Cannot credit a hypothetical or pre-eligibility fill")
        if s.latest_ms is None or time_ms > s.latest_ms:
            raise ValueError("Order must be a broker-confirmed observed event")
        if s.first_funded_ms is None:
            s.first_funded_ms = time_ms


@dataclass(frozen=True)
class MaturedOutcome:
    source: str
    entry_ms: int
    exit_ms: int
    received_ms: int
    realized_pnl: float
    funded: bool
    history_key: str


class ObservationLedger:
    """Progressive historical observation with causal lookback and shadow isolation.

    This records learning EVIDENCE only; strategy routing is owned by the original
    V1 algorithms. Provisional memory never authorizes Watchdog children/orders.
    """

    def __init__(self, lookback: int = 64, min_adaptive_samples: int = 16):
        if lookback < 1 or min_adaptive_samples < 1:
            raise ValueError("Lookback and evidence thresholds must be positive")
        self.lookback = lookback
        self.min_adaptive_samples = min_adaptive_samples
        self.funded: deque[MaturedOutcome] = deque(maxlen=lookback)
        self.shadow: deque[MaturedOutcome] = deque(maxlen=lookback)
        self.last_received_ms: Optional[int] = None
        self.keys: set[str] = set()

    def record(self, outcome: MaturedOutcome) -> None:
        if outcome.entry_ms >= outcome.exit_ms:
            raise ValueError("A completed outcome must exit after entry")
        if outcome.exit_ms > outcome.received_ms:
            raise ValueError("Future exit cannot update history")
        if self.last_received_ms is not None and outcome.received_ms < self.last_received_ms:
            raise ValueError("History updates must be chronologically received")
        if outcome.history_key in self.keys:
            raise ValueError("Duplicate completed outcome")
        if outcome.source not in ("SESSION", "ASIA", "WATCHDOG", "NATIVE", "RECOVERY"):
            raise ValueError("Unknown source/owner")
        self.last_received_ms = outcome.received_ms
        self.keys.add(outcome.history_key)
        (self.funded if outcome.funded else self.shadow).append(outcome)

    def snapshot(self) -> dict:
        """Observation diagnostics, NOT a traded strategy policy or unlock gate."""
        vals = tuple(x.realized_pnl for x in self.funded)
        return {
            "funded_closed_count": len(vals),
            "shadow_closed_count": len(self.shadow),
            "adaptive_observation_mature": len(vals) >= self.min_adaptive_samples,
            "recent_funded_expectancy": sum(vals) / len(vals) if vals else None,
            "watchdog_unlock_from_shadow": False,
            "original_v1_default_does_not_wait_for_this_ledger": True,
        }