"""DAA033 C2D3-F: source-native, month-blind JAN039 S26/S27 L3 policy.

This faithfully ports ONLY the accepted source IDs' L3 first executable
profitable-exit and admission-cap rules from the literal frozen JAN039
selected source-research artifact. It NEVER recreates upstream original
S26/S27 proposals, modifies native L2 classifiers, or claims V1 profitability.

Rules execute on any date given identical source, observed 10-minute phase,
actual funded position inventory, and current validated as-of state. January
is dataset provenance, not a live feature. S26/S27 original sources must be
recovered independently; this module cannot fabricate a candidate.
"""
from __future__ import annotations
from dataclasses import replace
from typing import Iterable
from v1_funded_core_033c import Quote, Structure, Proposal, Position, Close, FundedEngine

S26 = 'ORIG_SOURCE_26'
S27 = 'ORIG_SOURCE_27'
# Frozen JAN039_SELECTED_VERIFIED.json best-DD source proposal research frontier.
# This remains research-only until original signal + physical all-L0-L7 parity.
S26_LIMIT = 432
S26_NET_FIRST_HIT = 35.0
S27_NET_FIRST_HIT_BY_PHASE = {0: 60.0, 2: 50.0, 3: 50.0, 4: 35.0}
S27_POSITION_CAP_BY_PHASE = {0: 224, 5: 128}


def original_phase(q: Quote) -> int:
    """Original JAN039 ((t[E]//600000)%6), independent of date/month."""
    return (q.time_ms // 600000) % 6


class SourceNativeS26S27Policy:
    """Wrap fully independent source adapter; L7 alone owns actual admission.

    Cap checks include open *physically funded* positions, never hypothetical
    source outcomes. No cap or profit results are credited for denied proposals.
    Source future events remain causal and generated by the wrapped producer.
    """
    def __init__(self, upstream):
        self.upstream = upstream
        self._phase_by_funded_id: dict[int, int] = {}
        self.denied_source_cap = 0
        self.forwarded = 0

    def on_market_quote(self, q: Quote, engine: FundedEngine) -> None:
        callback = getattr(self.upstream, 'on_market_quote', None)
        if callback is not None:
            callback(q, engine)

    def propose(self, q: Quote, s: Structure, engine: FundedEngine) -> Iterable[Proposal]:
        if not s.valid_at(q.time_ms):
            return ()
        phase = original_phase(q)
        open_s26 = sum(p.source == S26 for p in engine.positions.values())
        open_s27_phase = sum(p.source == S27 and
                              self._phase_by_funded_id.get(p.id) == phase
                              for p in engine.positions.values())
        out = []
        reserved_s26 = 0
        reserved_s27_phase = 0
        for p in self.upstream.propose(q, s, engine):
            # All other original sources go to the SAME global physical governor.
            if p.source == S26:
                if open_s26 + reserved_s26 >= S26_LIMIT:
                    self.denied_source_cap += 1
                    continue
                # Frozen source uses executable close NET of a $0.02 roundtrip.
                # Native L7 TP compares raw GROSS quote mark: add the fee.
                p = replace(p, tp_usd=S26_NET_FIRST_HIT +
                            engine.limits.commission_roundtrip_usd)
                reserved_s26 += 1
            elif p.source == S27:
                cap = S27_POSITION_CAP_BY_PHASE.get(phase)
                if cap is not None and open_s27_phase + reserved_s27_phase >= cap:
                    self.denied_source_cap += 1
                    continue
                net_tp = S27_NET_FIRST_HIT_BY_PHASE.get(phase)
                if net_tp is not None:
                    p = replace(p, tp_usd=net_tp +
                                engine.limits.commission_roundtrip_usd)
                reserved_s27_phase += 1
            out.append(p)
            self.forwarded += 1
        return tuple(out)

    def on_funded_entry(self, pos: Position, q: Quote, s: Structure, engine: FundedEngine) -> None:
        if pos.source == S27:
            self._phase_by_funded_id[pos.id] = original_phase(q)
        callback = getattr(self.upstream, 'on_funded_entry', None)
        if callback is not None:
            callback(pos, q, s, engine)

    def on_funded_close(self, close: Close, engine: FundedEngine) -> None:
        self._phase_by_funded_id.pop(close.position_id, None)
        self.upstream.on_funded_close(close, engine)
